export default 
{
    /*Producto */
    accesorio:'ACCESORIOS',
    repuesto: 'REPUESTOS',
    marca : 'Marca de accesorio:',
    modelo : 'Modelo del vehículo :',
    tipoAc:'Tipo de accesorio :',
    filtroAcs:'FILTRAR ACCESORIOS',
    filtroRep:'FILTRAR REPUESTOS',
    /*Condiciones */
    titleCondiciones:'Terminos y condiciones MITSUI',
    containerCondiciones1:'El presente documento establece las condiciones mediante las cuales se regirá el uso de la aplicación móvil: Mitsui, la cual es operada por <b>Mitsui Automotriz S.A.</b>, compañía constituida en Perú y domiciliada en la ciudad de Lima y que actúa en representación de las compañías <b>Toyota, Hino y Lexus.</b>',
    containerCondiciones2:'<br><br>La aplicación funcionará como un nuevo canal para la realización de ciertas actividades descritas más adelante con el objeto de facilitar el acceso a los clientes de las compañías de <b>Mitsui Automotriz.</b>',
    containerCondiciones3:'<br><br>El usuario se compromete a leer los términos y condiciones aquí establecidas, previamente a la descarga de la aplicación, por tanto, en caso de realizar la instalación se entiende que cuenta con el conocimiento integral de este documento y la consecuente aceptación de la totalidad de sus estipulaciones.',
    containerCondiciones4:'<br><br>El Usuario reconoce que el ingreso de su información personal, y los datos que contiene la aplicación a su disposición respecto a los productos activos con las compañías del <b>Mitsui Automotriz en el Perú</b>, la realizan de manera voluntaria, quienes optan por acceder a esta aplicación en Perú o desde fuera del territorio nacional, lo hacen por iniciativa propia y son responsables del cumplimiento de las leyes locales, en la medida en que dichas leyes sean aplicables en su correspondiente país. En caso de que se acceda por parte de menores de edad, deben contar con la supervisión de un adulto en todo momento desde la descarga y durante el uso de la aplicación, en el evento en que no se cumpla esta condición, le agradecemos no hacer uso de la aplicación.',
    containerCondiciones5:'<br><b>ALCANSE Y USO</b><br><br>El usuario deberá contar con un dispositivo móvil inteligente (Smartphone) o Tableta con sistema operativo Android o IOS, cualquiera de estos con acceso a internet, ambos seguros y confiables. Mitsui Automotriz, no será responsable por la seguridad de los equipos Smartphone propiedad de los usuarios utilizados para el acceso al canal, ni por la disponibilidad del servicio en los dispositivos en los cuales se descargue la aplicación.',
    containerCondiciones6:'<br><br>En la forma permitida por la ley, los materiales de la aplicación se suministran sin garantía de ningún género, expresa o implícita, incluyendo sin limitación las garantías de calidad satisfactoria, comerciabilidad, adecuación para un fin particular o no infracción, por tanto, Mitsui Automotriz no garantiza el funcionamiento adecuado en los distintos sistemas operativos o dispositivos en los cuales se haga uso de la aplicación.',
    containerCondiciones7:'<br><br>Para acceder al portal, EL CLIENTE contará con Usuario y Clave, que lo identifica en su relación con <b>Mitsui Automotriz.</b>',
    containerCondiciones8:'<br><b>OBLIGACIONES DE LOS USUARIOS</b><br><br>El Usuario se obliga a usar la aplicación y los contenidos encontrados en ella de una manera diligente, correcta, lícita y en especial, se compromete a NO realizar las conductas descritas a continuación:<br>',
    containerCondiciones9:'<ul>'+
                          '<li>(a) Utilizar los contenidos de forma, con fines o efectos contrarios a la ley, a la moral y a las buenas costumbres generalmente aceptadas o al orden público.</li><br>'+
                          '<li>(b) Reproducir, copiar, representar, utilizar, distribuir, transformar o modificar los contenidos de la aplicación, por cualquier procedimiento o sobre cualquier soporte, total o parcial, o permitir el acceso del público a través de cualquier modalidad de comunicación pública.</li><br>'+
                          '<li>(c) Utilizar los contenidos de cualquier manera que entrañen un riesgo de daño o inutilización de la aplicación o de los contenidos o de terceros.</li><br>'+
                          '<li>(d) Suprimir, eludir o manipular el derecho de autor y demás datos identificativos de los derechos de autor incorporados a los contenidos, así como los dispositivos técnicos de protección, o cualesquiera mecanismos de información que pudieren tener los contenidos.</li><br>'+
                          '<li>(e) Emplear los contenidos y, en particular, la información de cualquier clase obtenida a través de la aplicación para distribuir, transmitir, remitir, modificar, rehusar o reportar la publicidad o los contenidos de esta con fines de venta directa o con cualquier otra clase de finalidad comercial, mensajes no solicitados dirigidos a una pluralidad de personas con independencia de su finalidad, así como comercializar o divulgar de cualquier modo dicha información.</li><br>'+
                          '<li>(f) No permitir que terceros ajenos a usted usen la aplicación móvil con su clave.</li><br>'+
                          '<li>(g) Utilizar la aplicación y los contenidos con fines lícitos y/o ilícitos, contrarios a lo establecido en estos Términos y Condiciones, o al uso mismo de la aplicación, que sean lesivos de los derechos e intereses de terceros, o que de cualquier forma puedan dañar, inutilizar, sobrecargar o deteriorar la aplicación y los contenidos o impedir la normal utilización o disfrute de esta y de los contenidos por parte de los usuarios.</li>'+
                          '</ul>',
    containerCondiciones10:'<b>PROPIEDAD INTELECTUAL</b><br><br>Todo el material informático, gráfico, publicitario, fotográfico, de multimedia, audiovisual y de diseño, así como todos los contenidos, textos y bases de datos puestos a su disposición en esta aplicación están protegidos por derechos de autor y/o propiedad industrial cuyo titular es Mitsui Automotriz S.A., o sus compañías filiales, vinculadas o subsidiarias, en algunos casos, de terceros que han autorizado su uso o explotación. Igualmente, el uso en la aplicación de algunos materiales de propiedad de terceros se encuentra expresamente autorizado por la ley o por dichos terceros. Todos los contenidos en la aplicación están protegidos por las normas sobre derecho de autor y por todas las normas nacionales e internacionales que le sean aplicables.',
    containerCondiciones11:'<br><br>Exceptuando lo expresamente estipulado en estos Términos y Condiciones, queda prohibido todo acto de copia, reproducción, modificación, creación de trabajos derivados, venta o distribución, exhibición de los contenidos de esta aplicación, de manera o por medio alguno, incluyendo, más no limitado a, medios electrónicos, mecánicos, de fotocopiado, de grabación o de cualquier otra índole, sin el permiso previo y por escrito de Mitsui Automotriz o del titular de los respectivos derechos.<br><br>En ningún caso estos Términos y Condiciones confieren derechos, licencias ni autorizaciones para realizar los actos anteriormente prohibidos. Cualquier uso no autorizado de los contenidos constituirá una violación del presente documento y a las normas vigentes sobre derechos de autor, a las normas vigentes nacionales e internacionales sobre Propiedad Industrial, y a cualquier otra que sea aplicable.',
    containerCondiciones12:'<br><b>MARCAS REGISTRADAS</b><br><br>Todas las marcas, logotipos y anagramas mostrados en este sitio son propiedad de Mitsui Automotriz S.A. o de terceras empresas ligadas. Se prohíbe usarlos, descargarlos permanentemente, copiarlos o distribuirlos por cualquier medio sin el permiso escrito de Mitsui Automotriz S.A. o de la tercera empresa.',
    containerCondiciones13:'<br><b>ACCIONES JUDICIALES</b><br><br>Mitsui Automotriz S.A. se reserva la posibilidad de ejercer las acciones judiciales que correspondan contra los usuarios que violen o infrinjan los derechos de propiedad intelectual e industrial.',
    containerCondiciones14:'<br><b>LICENCIA PARA COPIAR PARA USO PERSONAL</b><br><br>Usted podrá leer, visualizar, imprimir y descargar el material de sus productos.<br><br>Ninguna parte de la aplicación podrá ser reproducida o transmitida o almacenada en otro sitio web o en otra forma de sistema de recuperación electrónico.<br><br>Ya sea que se reconozca específicamente o no, las marcas comerciales, las marcas de servicio y los logos visualizados en esta aplicación pertenecen al grupo de compañías Mitsui Automotriz, sus socios promocionales u otros terceros.<br><br>Mitsui Automotriz  no interfiere, no toma decisiones, ni garantiza las relaciones que los usuarios lleguen a sostener o las vinculaciones con terceros que pauten y/o promocionen sus productos y servicios. Estas marcas de terceros se utilizan solamente para identificar los productos y servicios de sus respectivos propietarios y el patrocinio o el aval por parte de Mitsui Automotriz no se deben inferir con el uso de estas marcas comerciales.',
    containerCondiciones15:'<br><b>USO DE INFORMACIÓN Y PRIVACIDAD</b><br><br>Con la descarga de la APP usted acepta y autoriza que Mitsui Automotriz  S.A., utilice sus datos en calidad de responsable del tratamiento para fines derivados de la ejecución de la APP. Mitsui Automotriz  S.A informa que podrá ejercer sus derechos a conocer, actualizar, rectificar y suprimir su información personal; así como el derecho a revocar el consentimiento otorgado para el tratamiento de datos personales previstos en la Ley 29733 - PCM del 2011.',
    containerCondiciones16:'<br><b>SEGURIDAD</b><br><br>Mitsui Automotriz está comprometido en la protección de la seguridad de su información personal. Mitsui Automotriz  S.A. tiene implementados mecanismos de seguridad que aseguran la protección de la información personal, así como los accesos únicamente al personal y sistemas autorizados, también contra la pérdida, uso indebido y alteración de sus datos de usuario bajo nuestra administración.<br><br>Excepto como se indica a continuación, sólo personal autorizado tiene acceso a la información que nos proporciona. Además, hemos impuesto reglas estrictas a los empleados de Mitsui Automotriz  S.A. con acceso a las bases de datos que almacenan información del usuario o a los servidores que hospedan nuestros servicios.',
    containerCondiciones17:'<br><b>MODIFICACIÓN DE LA INFORMACIÓN</b><br><br><b>Mitsui Automotriz S.A.</b> se reserva la facultad y el derecho de actualizar, modificar o eliminar contenido o información de esta aplicación que estime conveniente, en parte o en su totalidad, pudiendo hacer uso de tal facultad en cualquier momento y sin previo aviso. Este derecho abarca los contenidos referidos a disponibilidad de modelos, colores, especificaciones, precio, disponibilidad de productos o servicios, equipamiento o en cuanto a las funcionalidades del sitio o de la información de actividades promocionales.<br><br><b>Mitsui Automotriz S.A.</b> se reserva el derecho de modificar las especificaciones, precios, colores y equipamientos de sus productos sin previo aviso, según el stock disponible.<br></br><b>Mitsui Automotriz S.A.</b> se reserva la facultad de modificar unilateralmente las condiciones y términos de uso de esta aplicación. La entrada en vigor de las modificaciones de las condiciones de uso se producirá desde el momento de su publicación en esta aplicación.',
    /*Politicas*/
    titlePoliticas:'Autorización de la Política de Protección de datos personales y tratamiento de los mismos.',
    containerPoliticasOne:'MITSUI AUTOMOTRIZ se compromete a velar por la CONFIDENCIALIDAD de los datos personales y antecedentes de los USUARIOS, así como hacer uso correcto de ellos; quedando prohibida cualquier transferencia no consentida. Estas obligaciones subsisten aun después de finalizadas las relaciones con MITSUI AUTOMOTRIZ',
    containerPoliticasTwo:'MITSUI AUTOMOTRIZ, declara su firme compromiso con la presente Política de Protección, así como de implementar mejoras constantes, con la finalidad de mantener niveles adecuados de seguridad de los datos personales de sus USUARIOS.',
    containerPoliticasTree:'En el momento del registro y por medio de la aceptación de las presentes políticas, el usuario toma conocimiento y autoriza a MITSUI AUTOMOTRIZ al tratamiento de sus datos personales para una mejor atención comercial y a contactarlos con la finalidad de mantenerlos informados sobre nuestros servicios y/o productos, tales como, promociones, campañas, programa de beneficios Club Mitsui, descuentos y otros relacionados. Asimismo, autoriza la transferencia de sus datos a Toyota del Perú (para fines técnicos y estadísticos), Entidades Financieras y/o Compañías de Seguros (para la adquisición de unidades y/o franquicias), Alianzas con otras empresas generadas como consecuencia de la ejecución de Convenios de Cooperación, empresas especializadas para el almacenaje y/o mensajería (para traslados, organización, custodia y archivo); manteniendo un nivel adecuado de protección y seguridad, de acuerdo a las normas de la materia y sus Políticas de Protección de Datos Personales.',


}